name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '📝 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🔧 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
      - 'dependabot'
  - title: '⚙️ Configuration'
    labels:
      - 'config'
      - 'configuration'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'fix'
      - 'documentation'
      - 'chore'
  default: patch

template: |
  ## What's Changed

  $CHANGES

  ## Deployment

  This release has been automatically deployed to GitHub Pages:
  🚀 **Live Site**: https://localgod.github.io/gitops/

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
      - 'docs/**/*'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
    title:
      - '/feature/i'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
    title:
      - '/chore/i'
  - label: 'dependencies'
    files:
      - 'package.json'
      - 'package-lock.json'
