github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true
gitConfig:
    alias.st: status
tasks:
  - name: setup
    init: |
      npm install -g npm@8.10.0 @sanity/cli
      npm install     

vscode:
  extensions:
    - octref.vetur
    - randomfractalsinc.geo-data-viewer
