github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true
gitConfig:
    alias.st: status
tasks:
  - before: |
      npm install --location=global npm@latest @sanity/cli@latest typescript@latest
      npm install    
  - name: Run dev env
    env:
      NODE_OPTIONS: --openssl-legacy-provider
    init: |
      npm run dev
vscode:
  extensions:
    - randomfractalsinc.geo-data-viewer
    - Vue.volar
