github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true
gitConfig:
    alias.st: status
tasks:
  - before: |
      npm install --location=global npm@8.12.2 @sanity/cli
      npm install    
  - init: |
      npm run dev

vscode:
  extensions:
    - randomfractalsinc.geo-data-viewer
    - johnsoncodehk.volar
