github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true
gitConfig:
    alias.st: status
tasks:
  - init: |
      npm install -g npm@8.1.4
      npm install     

vscode:
  extensions:
    - github.vscode-pull-request-github
    - octref.vetur
    - randomfractalsinc.geo-data-viewer
